/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'applicationType' : IDL.Text,
});
export const DisciplineRecord = IDL.Record({
  'id' : IDL.Nat,
  'resolvedStatus' : IDL.Bool,
  'action' : IDL.Text,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'incident' : IDL.Text,
});
export const ExamResult = IDL.Record({
  'id' : IDL.Nat,
  'marks' : IDL.Nat,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'year' : IDL.Nat,
  'grade' : IDL.Text,
  'maxMarks' : IDL.Nat,
  'examType' : IDL.Text,
});
export const FeeRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'paid' : IDL.Bool,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'lateFee' : IDL.Nat,
  'paidDate' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const LeaveRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'studentId' : IDL.Nat,
  'toDate' : IDL.Text,
  'fromDate' : IDL.Text,
  'reason' : IDL.Text,
});
export const Person = IDL.Record({
  'id' : IDL.Nat,
  'student_class' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'email' : IDL.Text,
  'rollNumber' : IDL.Nat,
  'address' : IDL.Text,
  'photo' : IDL.Text,
  'parentName' : IDL.Text,
});
export const SportRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'sportName' : IDL.Text,
  'level' : IDL.Text,
  'achievements' : IDL.Text,
});
export const StrengthRecord = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'subject' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewsItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'studentId' : IDL.Opt(IDL.Nat),
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addApplication' : IDL.Func([Application], [IDL.Nat], []),
  'addDisciplineRecord' : IDL.Func([DisciplineRecord], [IDL.Nat], []),
  'addExamResult' : IDL.Func([ExamResult], [IDL.Nat], []),
  'addFeeRecord' : IDL.Func([FeeRecord], [IDL.Nat], []),
  'addLeaveRecord' : IDL.Func([LeaveRecord], [IDL.Nat], []),
  'addNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPerson' : IDL.Func([Person], [IDL.Nat], []),
  'addSportRecord' : IDL.Func([SportRecord], [IDL.Nat], []),
  'addStrengthRecord' : IDL.Func([StrengthRecord], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteApplication' : IDL.Func([IDL.Nat], [], []),
  'deleteDisciplineRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteExamResult' : IDL.Func([IDL.Nat], [], []),
  'deleteFeeRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteLeaveRecord' : IDL.Func([IDL.Nat], [], []),
  'deletePerson' : IDL.Func([IDL.Nat], [], []),
  'deleteSportRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteStrengthRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getAllPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'getApplicationsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Application)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisciplineRecordsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DisciplineRecord)],
      ['query'],
    ),
  'getExamResultsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ExamResult)],
      ['query'],
    ),
  'getFeeRecordsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(FeeRecord)],
      ['query'],
    ),
  'getLeaveRecordsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaveRecord)],
      ['query'],
    ),
  'getNewsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(NewsItem)], ['query']),
  'getNewsById' : IDL.Func([IDL.Nat], [NewsItem], ['query']),
  'getPersonById' : IDL.Func([IDL.Nat], [Person], ['query']),
  'getPersonsByClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Person)],
      ['query'],
    ),
  'getSportRecordsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SportRecord)],
      ['query'],
    ),
  'getStrengthRecordsByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StrengthRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplication' : IDL.Func([IDL.Nat, Application], [], []),
  'updateDisciplineRecord' : IDL.Func([IDL.Nat, DisciplineRecord], [], []),
  'updateExamResult' : IDL.Func([IDL.Nat, ExamResult], [], []),
  'updateFeeRecord' : IDL.Func([IDL.Nat, FeeRecord], [], []),
  'updateLeaveRecord' : IDL.Func([IDL.Nat, LeaveRecord], [], []),
  'updateNews' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePerson' : IDL.Func([IDL.Nat, Person], [], []),
  'updateSportRecord' : IDL.Func([IDL.Nat, SportRecord], [], []),
  'updateStrengthRecord' : IDL.Func([IDL.Nat, StrengthRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'applicationType' : IDL.Text,
  });
  const DisciplineRecord = IDL.Record({
    'id' : IDL.Nat,
    'resolvedStatus' : IDL.Bool,
    'action' : IDL.Text,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'incident' : IDL.Text,
  });
  const ExamResult = IDL.Record({
    'id' : IDL.Nat,
    'marks' : IDL.Nat,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'year' : IDL.Nat,
    'grade' : IDL.Text,
    'maxMarks' : IDL.Nat,
    'examType' : IDL.Text,
  });
  const FeeRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'paid' : IDL.Bool,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'lateFee' : IDL.Nat,
    'paidDate' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const LeaveRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'studentId' : IDL.Nat,
    'toDate' : IDL.Text,
    'fromDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Person = IDL.Record({
    'id' : IDL.Nat,
    'student_class' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'email' : IDL.Text,
    'rollNumber' : IDL.Nat,
    'address' : IDL.Text,
    'photo' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const SportRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'sportName' : IDL.Text,
    'level' : IDL.Text,
    'achievements' : IDL.Text,
  });
  const StrengthRecord = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'subject' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewsItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'studentId' : IDL.Opt(IDL.Nat),
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addApplication' : IDL.Func([Application], [IDL.Nat], []),
    'addDisciplineRecord' : IDL.Func([DisciplineRecord], [IDL.Nat], []),
    'addExamResult' : IDL.Func([ExamResult], [IDL.Nat], []),
    'addFeeRecord' : IDL.Func([FeeRecord], [IDL.Nat], []),
    'addLeaveRecord' : IDL.Func([LeaveRecord], [IDL.Nat], []),
    'addNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addPerson' : IDL.Func([Person], [IDL.Nat], []),
    'addSportRecord' : IDL.Func([SportRecord], [IDL.Nat], []),
    'addStrengthRecord' : IDL.Func([StrengthRecord], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteApplication' : IDL.Func([IDL.Nat], [], []),
    'deleteDisciplineRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteExamResult' : IDL.Func([IDL.Nat], [], []),
    'deleteFeeRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteLeaveRecord' : IDL.Func([IDL.Nat], [], []),
    'deletePerson' : IDL.Func([IDL.Nat], [], []),
    'deleteSportRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteStrengthRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getAllPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'getApplicationsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisciplineRecordsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DisciplineRecord)],
        ['query'],
      ),
    'getExamResultsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ExamResult)],
        ['query'],
      ),
    'getFeeRecordsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'getLeaveRecordsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaveRecord)],
        ['query'],
      ),
    'getNewsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(NewsItem)], ['query']),
    'getNewsById' : IDL.Func([IDL.Nat], [NewsItem], ['query']),
    'getPersonById' : IDL.Func([IDL.Nat], [Person], ['query']),
    'getPersonsByClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Person)],
        ['query'],
      ),
    'getSportRecordsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SportRecord)],
        ['query'],
      ),
    'getStrengthRecordsByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StrengthRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplication' : IDL.Func([IDL.Nat, Application], [], []),
    'updateDisciplineRecord' : IDL.Func([IDL.Nat, DisciplineRecord], [], []),
    'updateExamResult' : IDL.Func([IDL.Nat, ExamResult], [], []),
    'updateFeeRecord' : IDL.Func([IDL.Nat, FeeRecord], [], []),
    'updateLeaveRecord' : IDL.Func([IDL.Nat, LeaveRecord], [], []),
    'updateNews' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePerson' : IDL.Func([IDL.Nat, Person], [], []),
    'updateSportRecord' : IDL.Func([IDL.Nat, SportRecord], [], []),
    'updateStrengthRecord' : IDL.Func([IDL.Nat, StrengthRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };