/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : string,
  'studentId' : bigint,
  'date' : string,
  'description' : string,
  'applicationType' : string,
}
export interface DisciplineRecord {
  'id' : bigint,
  'resolvedStatus' : boolean,
  'action' : string,
  'studentId' : bigint,
  'date' : string,
  'incident' : string,
}
export interface ExamResult {
  'id' : bigint,
  'marks' : bigint,
  'studentId' : bigint,
  'subject' : string,
  'year' : bigint,
  'grade' : string,
  'maxMarks' : bigint,
  'examType' : string,
}
export interface FeeRecord {
  'id' : bigint,
  'studentId' : bigint,
  'paid' : boolean,
  'dueDate' : string,
  'description' : string,
  'lateFee' : bigint,
  'paidDate' : [] | [string],
  'totalAmount' : bigint,
  'amount' : bigint,
  'transactionId' : [] | [string],
}
export interface LeaveRecord {
  'id' : bigint,
  'status' : string,
  'studentId' : bigint,
  'toDate' : string,
  'fromDate' : string,
  'reason' : string,
}
export interface NewsItem {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
  'category' : string,
}
export interface Person {
  'id' : bigint,
  'student_class' : string,
  'dateOfBirth' : string,
  'name' : string,
  'section' : string,
  'email' : string,
  'rollNumber' : bigint,
  'address' : string,
  'photo' : string,
  'parentName' : string,
}
export interface SportRecord {
  'id' : bigint,
  'studentId' : bigint,
  'sportName' : string,
  'level' : string,
  'achievements' : string,
}
export interface StrengthRecord {
  'id' : bigint,
  'studentId' : bigint,
  'subject' : string,
  'description' : string,
}
export interface UserProfile {
  'userType' : string,
  'studentId' : [] | [bigint],
  'userId' : bigint,
  'name' : string,
  'email' : string,
  'address' : string,
  'contactNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addApplication' : ActorMethod<[Application], bigint>,
  'addDisciplineRecord' : ActorMethod<[DisciplineRecord], bigint>,
  'addExamResult' : ActorMethod<[ExamResult], bigint>,
  'addFeeRecord' : ActorMethod<[FeeRecord], bigint>,
  'addLeaveRecord' : ActorMethod<[LeaveRecord], bigint>,
  'addNews' : ActorMethod<[string, string, string, string], bigint>,
  'addPerson' : ActorMethod<[Person], bigint>,
  'addSportRecord' : ActorMethod<[SportRecord], bigint>,
  'addStrengthRecord' : ActorMethod<[StrengthRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteApplication' : ActorMethod<[bigint], undefined>,
  'deleteDisciplineRecord' : ActorMethod<[bigint], undefined>,
  'deleteExamResult' : ActorMethod<[bigint], undefined>,
  'deleteFeeRecord' : ActorMethod<[bigint], undefined>,
  'deleteLeaveRecord' : ActorMethod<[bigint], undefined>,
  'deletePerson' : ActorMethod<[bigint], undefined>,
  'deleteSportRecord' : ActorMethod<[bigint], undefined>,
  'deleteStrengthRecord' : ActorMethod<[bigint], undefined>,
  'getAllNews' : ActorMethod<[], Array<NewsItem>>,
  'getAllPersons' : ActorMethod<[], Array<Person>>,
  'getApplicationsByStudent' : ActorMethod<[bigint], Array<Application>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisciplineRecordsByStudent' : ActorMethod<
    [bigint],
    Array<DisciplineRecord>
  >,
  'getExamResultsByStudent' : ActorMethod<[bigint], Array<ExamResult>>,
  'getFeeRecordsByStudent' : ActorMethod<[bigint], Array<FeeRecord>>,
  'getLeaveRecordsByStudent' : ActorMethod<[bigint], Array<LeaveRecord>>,
  'getNewsByCategory' : ActorMethod<[string], Array<NewsItem>>,
  'getNewsById' : ActorMethod<[bigint], NewsItem>,
  'getPersonById' : ActorMethod<[bigint], Person>,
  'getPersonsByClass' : ActorMethod<[string, string], Array<Person>>,
  'getSportRecordsByStudent' : ActorMethod<[bigint], Array<SportRecord>>,
  'getStrengthRecordsByStudent' : ActorMethod<[bigint], Array<StrengthRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplication' : ActorMethod<[bigint, Application], undefined>,
  'updateDisciplineRecord' : ActorMethod<[bigint, DisciplineRecord], undefined>,
  'updateExamResult' : ActorMethod<[bigint, ExamResult], undefined>,
  'updateFeeRecord' : ActorMethod<[bigint, FeeRecord], undefined>,
  'updateLeaveRecord' : ActorMethod<[bigint, LeaveRecord], undefined>,
  'updateNews' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updatePerson' : ActorMethod<[bigint, Person], undefined>,
  'updateSportRecord' : ActorMethod<[bigint, SportRecord], undefined>,
  'updateStrengthRecord' : ActorMethod<[bigint, StrengthRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];